### ISSUE TITLE
Changing sunxspex_fitting to fitting?

### ISSUE THREAD

**Issue by ianan** [sunpy/sunkit-spex#131]
### Describe the feature

Despite the name change we still have fitting called sunxspex_fitting, 
i.e. `from sunkit_spex.sunxspex_fitting.fitter import Fitter`

### Proposed solution

Maybe better to just call it fitting, so would do `from sunkit_spex.fitting.fitter import Fitter` ?

**Comment by samaloney** [comment]
I guess this can be close when #137 is merged will be `from sunkit.fitting_legacy import Fitter`

**Comment by settwi** [comment]
@samaloney let's close this?

**Comment by settwi** [comment]
@KriSun95 close?

**Comment by KriSun95** [comment]
> @KriSun95 close?

Yes, and thanks to @ianan for opening this!
