### ISSUE TITLE
Make an example gallery like Sunpy

### ISSUE THREAD

**Issue by settwi** [sunpy/sunkit-spex#141]
### Provide a general description of the issue or problem.

Sunpy has an awesome [example gallery](https://docs.sunpy.org/en/stable/generated/gallery/index.html) and I think new and experienced users use it all the time to see how to do basic and complicated things.

We should move the .ipynb examples to something that gets auto-built into examples by Sphinx.

**Comment by samaloney** [comment]
Closed by #150
