### ISSUE TITLE
The `sunxspex` default branch is still `master`

### ISSUE THREAD

**Issue by samaloney** [sunpy/sunkit-spex#73]
The `sunxspex` default branch is still `master` (that can probably be changed?) so the `help_url` is currently 404. The updated towncrier types here seem to correspond to the `sunpy/sunpy` version which is out of sync with the `sunpy/sunxspex` changelog readme (`changelog/README.rst`). Maybe this readme should also be re-synced with the sunpy version, and the URLs in `changelog_missing_long` and `type_incorrect_long` above updated to point to the README within the `sunxspex` repo.

_Originally posted by @ConorMacBride in https://github.com/sunpy/sunxspex/pull/70#discussion_r897796709_

**Comment by settwi** [comment]
Close?
